apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
    GREETING: Salem
    HOSTNAME: iamfromconfig
    ENVIRONMENT: default
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  DATABASE_URI: cG9zdGdyZXNxbCtwc3ljb3BnMjovL215dXNlcjpwYXNzd2RAcG9zdGdyZXM6NTQzMi9teWFwcAo=
