apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-py-app
  template:
    metadata:
      labels:
        app: hello-py-app
    spec:
      containers:
      - name: hello-py
        image: kkboranbay/user-crud-flask
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: DATABASE_URI
          - name: GREETING
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: GREETING
          - name: HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: HOSTNAME
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: ENVIRONMENT
        ports:
          - name: web
            containerPort: 9000