replicaCount: 1

image: kkboranbay/user-crud-flask

service:
  type: NodePort
  port: 9000

externalPostgresql:
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  postgresqlHost: "postgres-test"
  postgresqlPort: "5432"

GREETING: SALEMETSIZBE! 
ENVIRONMENT: TEST